language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; brew install openssl; brew link --force openssl; fi
env:
  - KOREBUILD_TEST_DNXCORE=true NO_PARALLEL_TEST_PROJECTS=E2ETests
install:
  - curl -sSL https://github.com/libuv/libuv/archive/v1.4.2.tar.gz | tar zxfv - -C /tmp && cd /tmp/libuv-1.4.2/
  - sh autogen.sh
  - ./configure --prefix=$HOME/libuvinstall
  - make
  - make install
  - export LD_LIBRARY_PATH="$HOME/libuvinstall/lib"
  - cd $OLDPWD
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
before_script:
  - chmod ugo+x build.sh
script:
  - ./build.sh verify